color_range_list:
  black:
    max:
    - 114
    - 137
    - 137
    min:
    - 41
    - 114
    - 111
  blue:
    max:
    - 233
    - 150
    - 111
    min:
    - 0
    - 88
    - 0
  green:
    max:
    - 255
    - 121
    - 195
    min:
    - 7
    - 11
    - 15
  purple:
    max:
    - 172
    - 187
    - 128
    min:
    - 0
    - 144
    - 79
  red:
    max:
    - 255
    - 251
    - 255
    min:
    - 18
    - 144
    - 98
  tennis:
    max:
    - 255
    - 116
    - 181
    min:
    - 19
    - 79
    - 140
  white:
    max:
    - 255
    - 155
    - 155
    min:
    - 110
    - 100
    - 100
  yellow:
    max:
    - 255
    - 177
    - 184
    min:
    - 195
    - 110
    - 146
